# Generated by Django 4.1.2 on 2022-11-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
