# Generated by Django 4.1.2 on 2022-11-03 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='apellidos',
            field=models.CharField(default='vacio', max_length=100, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirante',
            name='nacionalidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.nacionalidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirante',
            name='nombres',
            field=models.CharField(default='Juan', max_length=100, verbose_name='Nombres'),
            preserve_default=False,
        ),
    ]
