# Generated by Django 4.1.2 on 2022-11-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='foto',
            field=models.ImageField(null=True, upload_to='aspirantes'),
        ),
    ]
