# Generated by Django 4.1.2 on 2022-11-17 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maestria',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('plazo_inicio', models.DateField(verbose_name='plazo_inicio')),
                ('plazo_final', models.DateField(verbose_name='plazo_final')),
                ('url_prueba', models.CharField(max_length=250, verbose_name='url_prueba')),
            ],
        ),
        migrations.CreateModel(
            name='DirectorXMaestria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_director_pk_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.director')),
                ('codigo_maestria_pk_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.maestria')),
            ],
        ),
    ]
