# Generated by Django 4.1.2 on 2022-11-19 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('documento', models.CharField(max_length=100, unique=True, verbose_name='Documento de identidad')),
                ('foto', models.URLField(max_length=255, verbose_name='Foto de perfil')),
                ('egresado_ufps', models.BooleanField(default=False, verbose_name='¿es egresado de la UFPS?')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código de egresado')),
                ('es_extranjero', models.BooleanField(default=False, verbose_name='Extranjero')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maestria',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('plazo_inicio', models.DateField(verbose_name='plazo_inicio')),
                ('plazo_final', models.DateField(verbose_name='plazo_final')),
                ('url_prueba', models.CharField(max_length=250, verbose_name='url_prueba')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=50, verbose_name='Tipo de documento')),
            ],
        ),
        migrations.CreateModel(
            name='DirectorXMaestria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_director_pk_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.director')),
                ('codigo_maestria_pk_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.maestria')),
            ],
        ),
    ]
